// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/modules/face_geometry/protos/environment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe.FaceGeometry {

  /// <summary>Holder for reflection information generated from mediapipe/modules/face_geometry/protos/environment.proto</summary>
  public static partial class EnvironmentReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/modules/face_geometry/protos/environment.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnvironmentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhtZWRpYXBpcGUvbW9kdWxlcy9mYWNlX2dlb21ldHJ5L3Byb3Rvcy9lbnZp",
            "cm9ubWVudC5wcm90bxIXbWVkaWFwaXBlLmZhY2VfZ2VvbWV0cnkiTAoRUGVy",
            "c3BlY3RpdmVDYW1lcmESHAoUdmVydGljYWxfZm92X2RlZ3JlZXMYASABKAIS",
            "DAoEbmVhchgCIAEoAhILCgNmYXIYAyABKAIiogEKC0Vudmlyb25tZW50EksK",
            "FW9yaWdpbl9wb2ludF9sb2NhdGlvbhgBIAEoDjIsLm1lZGlhcGlwZS5mYWNl",
            "X2dlb21ldHJ5Lk9yaWdpblBvaW50TG9jYXRpb24SRgoScGVyc3BlY3RpdmVf",
            "Y2FtZXJhGAIgASgLMioubWVkaWFwaXBlLmZhY2VfZ2VvbWV0cnkuUGVyc3Bl",
            "Y3RpdmVDYW1lcmEqQgoTT3JpZ2luUG9pbnRMb2NhdGlvbhIWChJCT1RUT01f",
            "TEVGVF9DT1JORVIQARITCg9UT1BfTEVGVF9DT1JORVIQAkI9Ciljb20uZ29v",
            "Z2xlLm1lZGlhcGlwZS5tb2R1bGVzLmZhY2VnZW9tZXRyeUIQRW52aXJvbm1l",
            "bnRQcm90bw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Mediapipe.FaceGeometry.OriginPointLocation), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FaceGeometry.PerspectiveCamera), global::Mediapipe.FaceGeometry.PerspectiveCamera.Parser, new[]{ "VerticalFovDegrees", "Near", "Far" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FaceGeometry.Environment), global::Mediapipe.FaceGeometry.Environment.Parser, new[]{ "OriginPointLocation", "PerspectiveCamera" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Defines the (0, 0) origin point location of the environment.
  ///
  /// The variation in the origin point location can be traced back to the memory
  /// layout of the camera video frame buffers.
  ///
  /// Usually, the memory layout for most CPU (and also some GPU) camera video
  /// frame buffers results in having the (0, 0) origin point located in the
  /// Top Left corner.
  ///
  /// On the contrary, the memory layout for most GPU camera video frame buffers
  /// results in having the (0, 0) origin point located in the Bottom Left corner.
  ///
  /// Let's consider the following example:
  ///
  /// (A) ---------------+
  ///               ___  |
  ///  |     (1)    | |  |
  ///  |     / \    | |  |
  ///  |    |---|===|-|  |
  ///  |    |---|   | |  |
  ///  |   /     \  | |  |
  ///  |  |       | | |  |
  ///  |  |  (2)  |=| |  |
  ///  |  |       | | |  |
  ///  |  |_______| |_|  |
  ///  |   |@| |@|  | |  |
  ///  | ___________|_|_ |
  ///                    |
  /// (B) ---------------+
  ///
  /// On this example, (1) and (2) have the same X coordinate regardless of the
  /// origin point location. However, having the origin point located at (A)
  /// (Top Left corner) results in (1) having a smaller Y coordinate if compared to
  /// (2). Similarly, having the origin point located at (B) (Bottom Left corner)
  /// results in (1) having a greater Y coordinate if compared to (2).
  ///
  /// Providing the correct origin point location for your environment and making
  /// sure all the input landmarks are in-sync with this location is crucial
  /// for receiving the correct output face geometry and visual renders.
  /// </summary>
  public enum OriginPointLocation {
    [pbr::OriginalName("BOTTOM_LEFT_CORNER")] BottomLeftCorner = 1,
    [pbr::OriginalName("TOP_LEFT_CORNER")] TopLeftCorner = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// The perspective camera is defined through its vertical FOV angle and the
  /// Z-clipping planes. The aspect ratio is a runtime variable for the face
  /// geometry module and should be provided alongside the face landmarks in order
  /// to estimate the face geometry on a given frame.
  ///
  /// More info on Perspective Cameras:
  /// http://www.songho.ca/opengl/gl_projectionmatrix.html#perspective
  /// </summary>
  public sealed partial class PerspectiveCamera : pb::IMessage<PerspectiveCamera>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PerspectiveCamera> _parser = new pb::MessageParser<PerspectiveCamera>(() => new PerspectiveCamera());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PerspectiveCamera> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.FaceGeometry.EnvironmentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PerspectiveCamera() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PerspectiveCamera(PerspectiveCamera other) : this() {
      _hasBits0 = other._hasBits0;
      verticalFovDegrees_ = other.verticalFovDegrees_;
      near_ = other.near_;
      far_ = other.far_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PerspectiveCamera Clone() {
      return new PerspectiveCamera(this);
    }

    /// <summary>Field number for the "vertical_fov_degrees" field.</summary>
    public const int VerticalFovDegreesFieldNumber = 1;
    private readonly static float VerticalFovDegreesDefaultValue = 0F;

    private float verticalFovDegrees_;
    /// <summary>
    /// `0 &lt; vertical_fov_degrees &lt; 180`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VerticalFovDegrees {
      get { if ((_hasBits0 & 1) != 0) { return verticalFovDegrees_; } else { return VerticalFovDegreesDefaultValue; } }
      set {
        _hasBits0 |= 1;
        verticalFovDegrees_ = value;
      }
    }
    /// <summary>Gets whether the "vertical_fov_degrees" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVerticalFovDegrees {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "vertical_fov_degrees" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVerticalFovDegrees() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "near" field.</summary>
    public const int NearFieldNumber = 2;
    private readonly static float NearDefaultValue = 0F;

    private float near_;
    /// <summary>
    /// `0 &lt; near &lt; far`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Near {
      get { if ((_hasBits0 & 2) != 0) { return near_; } else { return NearDefaultValue; } }
      set {
        _hasBits0 |= 2;
        near_ = value;
      }
    }
    /// <summary>Gets whether the "near" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNear {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "near" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNear() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "far" field.</summary>
    public const int FarFieldNumber = 3;
    private readonly static float FarDefaultValue = 0F;

    private float far_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Far {
      get { if ((_hasBits0 & 4) != 0) { return far_; } else { return FarDefaultValue; } }
      set {
        _hasBits0 |= 4;
        far_ = value;
      }
    }
    /// <summary>Gets whether the "far" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFar {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "far" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFar() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PerspectiveCamera);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PerspectiveCamera other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VerticalFovDegrees, other.VerticalFovDegrees)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Near, other.Near)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Far, other.Far)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVerticalFovDegrees) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VerticalFovDegrees);
      if (HasNear) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Near);
      if (HasFar) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Far);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasVerticalFovDegrees) {
        output.WriteRawTag(13);
        output.WriteFloat(VerticalFovDegrees);
      }
      if (HasNear) {
        output.WriteRawTag(21);
        output.WriteFloat(Near);
      }
      if (HasFar) {
        output.WriteRawTag(29);
        output.WriteFloat(Far);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasVerticalFovDegrees) {
        output.WriteRawTag(13);
        output.WriteFloat(VerticalFovDegrees);
      }
      if (HasNear) {
        output.WriteRawTag(21);
        output.WriteFloat(Near);
      }
      if (HasFar) {
        output.WriteRawTag(29);
        output.WriteFloat(Far);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasVerticalFovDegrees) {
        size += 1 + 4;
      }
      if (HasNear) {
        size += 1 + 4;
      }
      if (HasFar) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PerspectiveCamera other) {
      if (other == null) {
        return;
      }
      if (other.HasVerticalFovDegrees) {
        VerticalFovDegrees = other.VerticalFovDegrees;
      }
      if (other.HasNear) {
        Near = other.Near;
      }
      if (other.HasFar) {
        Far = other.Far;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            VerticalFovDegrees = input.ReadFloat();
            break;
          }
          case 21: {
            Near = input.ReadFloat();
            break;
          }
          case 29: {
            Far = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            VerticalFovDegrees = input.ReadFloat();
            break;
          }
          case 21: {
            Near = input.ReadFloat();
            break;
          }
          case 29: {
            Far = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Environment : pb::IMessage<Environment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Environment> _parser = new pb::MessageParser<Environment>(() => new Environment());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Environment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.FaceGeometry.EnvironmentReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Environment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Environment(Environment other) : this() {
      _hasBits0 = other._hasBits0;
      originPointLocation_ = other.originPointLocation_;
      perspectiveCamera_ = other.perspectiveCamera_ != null ? other.perspectiveCamera_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Environment Clone() {
      return new Environment(this);
    }

    /// <summary>Field number for the "origin_point_location" field.</summary>
    public const int OriginPointLocationFieldNumber = 1;
    private readonly static global::Mediapipe.FaceGeometry.OriginPointLocation OriginPointLocationDefaultValue = global::Mediapipe.FaceGeometry.OriginPointLocation.BottomLeftCorner;

    private global::Mediapipe.FaceGeometry.OriginPointLocation originPointLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.FaceGeometry.OriginPointLocation OriginPointLocation {
      get { if ((_hasBits0 & 1) != 0) { return originPointLocation_; } else { return OriginPointLocationDefaultValue; } }
      set {
        _hasBits0 |= 1;
        originPointLocation_ = value;
      }
    }
    /// <summary>Gets whether the "origin_point_location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOriginPointLocation {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "origin_point_location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOriginPointLocation() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "perspective_camera" field.</summary>
    public const int PerspectiveCameraFieldNumber = 2;
    private global::Mediapipe.FaceGeometry.PerspectiveCamera perspectiveCamera_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.FaceGeometry.PerspectiveCamera PerspectiveCamera {
      get { return perspectiveCamera_; }
      set {
        perspectiveCamera_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Environment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Environment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OriginPointLocation != other.OriginPointLocation) return false;
      if (!object.Equals(PerspectiveCamera, other.PerspectiveCamera)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOriginPointLocation) hash ^= OriginPointLocation.GetHashCode();
      if (perspectiveCamera_ != null) hash ^= PerspectiveCamera.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOriginPointLocation) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OriginPointLocation);
      }
      if (perspectiveCamera_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PerspectiveCamera);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOriginPointLocation) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OriginPointLocation);
      }
      if (perspectiveCamera_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PerspectiveCamera);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOriginPointLocation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OriginPointLocation);
      }
      if (perspectiveCamera_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PerspectiveCamera);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Environment other) {
      if (other == null) {
        return;
      }
      if (other.HasOriginPointLocation) {
        OriginPointLocation = other.OriginPointLocation;
      }
      if (other.perspectiveCamera_ != null) {
        if (perspectiveCamera_ == null) {
          PerspectiveCamera = new global::Mediapipe.FaceGeometry.PerspectiveCamera();
        }
        PerspectiveCamera.MergeFrom(other.PerspectiveCamera);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OriginPointLocation = (global::Mediapipe.FaceGeometry.OriginPointLocation) input.ReadEnum();
            break;
          }
          case 18: {
            if (perspectiveCamera_ == null) {
              PerspectiveCamera = new global::Mediapipe.FaceGeometry.PerspectiveCamera();
            }
            input.ReadMessage(PerspectiveCamera);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OriginPointLocation = (global::Mediapipe.FaceGeometry.OriginPointLocation) input.ReadEnum();
            break;
          }
          case 18: {
            if (perspectiveCamera_ == null) {
              PerspectiveCamera = new global::Mediapipe.FaceGeometry.PerspectiveCamera();
            }
            input.ReadMessage(PerspectiveCamera);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
