// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/modules/objectron/calculators/frame_annotation_to_rect_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/modules/objectron/calculators/frame_annotation_to_rect_calculator.proto</summary>
  public static partial class FrameAnnotationToRectCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/modules/objectron/calculators/frame_annotation_to_rect_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameAnnotationToRectCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClFtZWRpYXBpcGUvbW9kdWxlcy9vYmplY3Ryb24vY2FsY3VsYXRvcnMvZnJh",
            "bWVfYW5ub3RhdGlvbl90b19yZWN0X2NhbGN1bGF0b3IucHJvdG8SCW1lZGlh",
            "cGlwZRokbWVkaWFwaXBlL2ZyYW1ld29yay9jYWxjdWxhdG9yLnByb3RvIr8B",
            "CiZGcmFtZUFubm90YXRpb25Ub1JlY3RDYWxjdWxhdG9yT3B0aW9ucxIZCg1v",
            "ZmZfdGhyZXNob2xkGAEgASgCOgI0MBIYCgxvbl90aHJlc2hvbGQYAiABKAI6",
            "AjQxMmAKA2V4dBIcLm1lZGlhcGlwZS5DYWxjdWxhdG9yT3B0aW9ucxibk52h",
            "ASABKAsyMS5tZWRpYXBpcGUuRnJhbWVBbm5vdGF0aW9uVG9SZWN0Q2FsY3Vs",
            "YXRvck9wdGlvbnM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.FrameAnnotationToRectCalculatorOptions), global::Mediapipe.FrameAnnotationToRectCalculatorOptions.Parser, new[]{ "OffThreshold", "OnThreshold" }, null, null, new pb::Extension[] { global::Mediapipe.FrameAnnotationToRectCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FrameAnnotationToRectCalculatorOptions : pb::IMessage<FrameAnnotationToRectCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrameAnnotationToRectCalculatorOptions> _parser = new pb::MessageParser<FrameAnnotationToRectCalculatorOptions>(() => new FrameAnnotationToRectCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrameAnnotationToRectCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.FrameAnnotationToRectCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameAnnotationToRectCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameAnnotationToRectCalculatorOptions(FrameAnnotationToRectCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      offThreshold_ = other.offThreshold_;
      onThreshold_ = other.onThreshold_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrameAnnotationToRectCalculatorOptions Clone() {
      return new FrameAnnotationToRectCalculatorOptions(this);
    }

    /// <summary>Field number for the "off_threshold" field.</summary>
    public const int OffThresholdFieldNumber = 1;
    private readonly static float OffThresholdDefaultValue = 40F;

    private float offThreshold_;
    /// <summary>
    /// The threshold to use when top-view is off,to enable hysteresis,
    /// It's required that off_threshold &lt;= on_threshold.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float OffThreshold {
      get { if ((_hasBits0 & 1) != 0) { return offThreshold_; } else { return OffThresholdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        offThreshold_ = value;
      }
    }
    /// <summary>Gets whether the "off_threshold" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOffThreshold {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "off_threshold" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOffThreshold() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "on_threshold" field.</summary>
    public const int OnThresholdFieldNumber = 2;
    private readonly static float OnThresholdDefaultValue = 41F;

    private float onThreshold_;
    /// <summary>
    /// The threshold to use when top-view is on.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float OnThreshold {
      get { if ((_hasBits0 & 2) != 0) { return onThreshold_; } else { return OnThresholdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        onThreshold_ = value;
      }
    }
    /// <summary>Gets whether the "on_threshold" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOnThreshold {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "on_threshold" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOnThreshold() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrameAnnotationToRectCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrameAnnotationToRectCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OffThreshold, other.OffThreshold)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OnThreshold, other.OnThreshold)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOffThreshold) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OffThreshold);
      if (HasOnThreshold) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OnThreshold);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOffThreshold) {
        output.WriteRawTag(13);
        output.WriteFloat(OffThreshold);
      }
      if (HasOnThreshold) {
        output.WriteRawTag(21);
        output.WriteFloat(OnThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOffThreshold) {
        output.WriteRawTag(13);
        output.WriteFloat(OffThreshold);
      }
      if (HasOnThreshold) {
        output.WriteRawTag(21);
        output.WriteFloat(OnThreshold);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOffThreshold) {
        size += 1 + 4;
      }
      if (HasOnThreshold) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrameAnnotationToRectCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasOffThreshold) {
        OffThreshold = other.OffThreshold;
      }
      if (other.HasOnThreshold) {
        OnThreshold = other.OnThreshold;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            OffThreshold = input.ReadFloat();
            break;
          }
          case 21: {
            OnThreshold = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            OffThreshold = input.ReadFloat();
            break;
          }
          case 21: {
            OnThreshold = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the FrameAnnotationToRectCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FrameAnnotationToRectCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.FrameAnnotationToRectCalculatorOptions>(338119067, pb::FieldCodec.ForMessage(2704952538, global::Mediapipe.FrameAnnotationToRectCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
