// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/modules/objectron/calculators/tensors_to_objects_calculator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe {

  /// <summary>Holder for reflection information generated from mediapipe/modules/objectron/calculators/tensors_to_objects_calculator.proto</summary>
  public static partial class TensorsToObjectsCalculatorReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/modules/objectron/calculators/tensors_to_objects_calculator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TensorsToObjectsCalculatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkttZWRpYXBpcGUvbW9kdWxlcy9vYmplY3Ryb24vY2FsY3VsYXRvcnMvdGVu",
            "c29yc190b19vYmplY3RzX2NhbGN1bGF0b3IucHJvdG8SCW1lZGlhcGlwZRok",
            "bWVkaWFwaXBlL2ZyYW1ld29yay9jYWxjdWxhdG9yLnByb3RvGkNtZWRpYXBp",
            "cGUvbW9kdWxlcy9vYmplY3Ryb24vY2FsY3VsYXRvcnMvYmVsaWVmX2RlY29k",
            "ZXJfY29uZmlnLnByb3RvIogCCiFUZW5zb3JzVG9PYmplY3RzQ2FsY3VsYXRv",
            "ck9wdGlvbnMSEwoLbnVtX2NsYXNzZXMYASABKAUSFQoNbnVtX2tleXBvaW50",
            "cxgCIAEoBRIiChdudW1fdmFsdWVzX3Blcl9rZXlwb2ludBgDIAEoBToBMhI2",
            "Cg5kZWNvZGVyX2NvbmZpZxgEIAEoCzIeLm1lZGlhcGlwZS5CZWxpZWZEZWNv",
            "ZGVyQ29uZmlnMlsKA2V4dBIcLm1lZGlhcGlwZS5DYWxjdWxhdG9yT3B0aW9u",
            "cxjU6refASABKAsyLC5tZWRpYXBpcGUuVGVuc29yc1RvT2JqZWN0c0NhbGN1",
            "bGF0b3JPcHRpb25z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.CalculatorReflection.Descriptor, global::Mediapipe.BeliefDecoderConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.TensorsToObjectsCalculatorOptions), global::Mediapipe.TensorsToObjectsCalculatorOptions.Parser, new[]{ "NumClasses", "NumKeypoints", "NumValuesPerKeypoint", "DecoderConfig" }, null, null, new pb::Extension[] { global::Mediapipe.TensorsToObjectsCalculatorOptions.Extensions.Ext }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TensorsToObjectsCalculatorOptions : pb::IMessage<TensorsToObjectsCalculatorOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TensorsToObjectsCalculatorOptions> _parser = new pb::MessageParser<TensorsToObjectsCalculatorOptions>(() => new TensorsToObjectsCalculatorOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TensorsToObjectsCalculatorOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.TensorsToObjectsCalculatorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToObjectsCalculatorOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToObjectsCalculatorOptions(TensorsToObjectsCalculatorOptions other) : this() {
      _hasBits0 = other._hasBits0;
      numClasses_ = other.numClasses_;
      numKeypoints_ = other.numKeypoints_;
      numValuesPerKeypoint_ = other.numValuesPerKeypoint_;
      decoderConfig_ = other.decoderConfig_ != null ? other.decoderConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensorsToObjectsCalculatorOptions Clone() {
      return new TensorsToObjectsCalculatorOptions(this);
    }

    /// <summary>Field number for the "num_classes" field.</summary>
    public const int NumClassesFieldNumber = 1;
    private readonly static int NumClassesDefaultValue = 0;

    private int numClasses_;
    /// <summary>
    /// The number of output classes predicted by the detection model.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumClasses {
      get { if ((_hasBits0 & 1) != 0) { return numClasses_; } else { return NumClassesDefaultValue; } }
      set {
        _hasBits0 |= 1;
        numClasses_ = value;
      }
    }
    /// <summary>Gets whether the "num_classes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumClasses {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "num_classes" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumClasses() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "num_keypoints" field.</summary>
    public const int NumKeypointsFieldNumber = 2;
    private readonly static int NumKeypointsDefaultValue = 0;

    private int numKeypoints_;
    /// <summary>
    /// The number of predicted keypoints.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumKeypoints {
      get { if ((_hasBits0 & 2) != 0) { return numKeypoints_; } else { return NumKeypointsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        numKeypoints_ = value;
      }
    }
    /// <summary>Gets whether the "num_keypoints" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumKeypoints {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "num_keypoints" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumKeypoints() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "num_values_per_keypoint" field.</summary>
    public const int NumValuesPerKeypointFieldNumber = 3;
    private readonly static int NumValuesPerKeypointDefaultValue = 2;

    private int numValuesPerKeypoint_;
    /// <summary>
    /// The dimension of each keypoint, e.g. number of values predicted for each
    /// keypoint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumValuesPerKeypoint {
      get { if ((_hasBits0 & 4) != 0) { return numValuesPerKeypoint_; } else { return NumValuesPerKeypointDefaultValue; } }
      set {
        _hasBits0 |= 4;
        numValuesPerKeypoint_ = value;
      }
    }
    /// <summary>Gets whether the "num_values_per_keypoint" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumValuesPerKeypoint {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "num_values_per_keypoint" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumValuesPerKeypoint() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "decoder_config" field.</summary>
    public const int DecoderConfigFieldNumber = 4;
    private global::Mediapipe.BeliefDecoderConfig decoderConfig_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.BeliefDecoderConfig DecoderConfig {
      get { return decoderConfig_; }
      set {
        decoderConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TensorsToObjectsCalculatorOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TensorsToObjectsCalculatorOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumClasses != other.NumClasses) return false;
      if (NumKeypoints != other.NumKeypoints) return false;
      if (NumValuesPerKeypoint != other.NumValuesPerKeypoint) return false;
      if (!object.Equals(DecoderConfig, other.DecoderConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasNumClasses) hash ^= NumClasses.GetHashCode();
      if (HasNumKeypoints) hash ^= NumKeypoints.GetHashCode();
      if (HasNumValuesPerKeypoint) hash ^= NumValuesPerKeypoint.GetHashCode();
      if (decoderConfig_ != null) hash ^= DecoderConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasNumClasses) {
        output.WriteRawTag(8);
        output.WriteInt32(NumClasses);
      }
      if (HasNumKeypoints) {
        output.WriteRawTag(16);
        output.WriteInt32(NumKeypoints);
      }
      if (HasNumValuesPerKeypoint) {
        output.WriteRawTag(24);
        output.WriteInt32(NumValuesPerKeypoint);
      }
      if (decoderConfig_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DecoderConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasNumClasses) {
        output.WriteRawTag(8);
        output.WriteInt32(NumClasses);
      }
      if (HasNumKeypoints) {
        output.WriteRawTag(16);
        output.WriteInt32(NumKeypoints);
      }
      if (HasNumValuesPerKeypoint) {
        output.WriteRawTag(24);
        output.WriteInt32(NumValuesPerKeypoint);
      }
      if (decoderConfig_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DecoderConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasNumClasses) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumClasses);
      }
      if (HasNumKeypoints) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumKeypoints);
      }
      if (HasNumValuesPerKeypoint) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumValuesPerKeypoint);
      }
      if (decoderConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DecoderConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TensorsToObjectsCalculatorOptions other) {
      if (other == null) {
        return;
      }
      if (other.HasNumClasses) {
        NumClasses = other.NumClasses;
      }
      if (other.HasNumKeypoints) {
        NumKeypoints = other.NumKeypoints;
      }
      if (other.HasNumValuesPerKeypoint) {
        NumValuesPerKeypoint = other.NumValuesPerKeypoint;
      }
      if (other.decoderConfig_ != null) {
        if (decoderConfig_ == null) {
          DecoderConfig = new global::Mediapipe.BeliefDecoderConfig();
        }
        DecoderConfig.MergeFrom(other.DecoderConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NumClasses = input.ReadInt32();
            break;
          }
          case 16: {
            NumKeypoints = input.ReadInt32();
            break;
          }
          case 24: {
            NumValuesPerKeypoint = input.ReadInt32();
            break;
          }
          case 34: {
            if (decoderConfig_ == null) {
              DecoderConfig = new global::Mediapipe.BeliefDecoderConfig();
            }
            input.ReadMessage(DecoderConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NumClasses = input.ReadInt32();
            break;
          }
          case 16: {
            NumKeypoints = input.ReadInt32();
            break;
          }
          case 24: {
            NumValuesPerKeypoint = input.ReadInt32();
            break;
          }
          case 34: {
            if (decoderConfig_ == null) {
              DecoderConfig = new global::Mediapipe.BeliefDecoderConfig();
            }
            input.ReadMessage(DecoderConfig);
            break;
          }
        }
      }
    }
    #endif

    #region Extensions
    /// <summary>Container for extensions for other messages declared in the TensorsToObjectsCalculatorOptions message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Extensions {
      public static readonly pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.TensorsToObjectsCalculatorOptions> Ext =
        new pb::Extension<global::Mediapipe.CalculatorOptions, global::Mediapipe.TensorsToObjectsCalculatorOptions>(334361940, pb::FieldCodec.ForMessage(2674895522, global::Mediapipe.TensorsToObjectsCalculatorOptions.Parser));
    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
